services:

  database:
    image: postgres:16.1
    environment:
      POSTGRES_DB: inventory
      POSTGRES_USER: inventory
      POSTGRES_PASSWORD: inventory
      PGDATA: /var/lib/postgresql/data
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - 2345:5432
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U sfin" ]
      interval: 10s
      timeout: 5s
      retries: 5

  db-init:
    image: postgres:16.1
    depends_on:
      database:
        condition: service_healthy
    environment:
      PGPASSWORD: sfin
    command: |
      bash -c "
      # Check if inventory database already exists
      if psql -h database -U inventory -d inventory -lqt | cut -d \| -f 1 | grep -qw inventory; then
        echo 'Database inventory already exists, skipping creation and import'
      else
        echo 'Creating inventory database and importing oauth2.sql'
        psql -h database -U inventory -d inventory -c 'CREATE DATABASE inventory;'
      fi
      "
    volumes:
      - ./application/src/main/resources/db/changelog/static:/sql

volumes:
  db_data: